Repository codesquad-member-2020/airbnb-09, pull requests merged in 2020-05, with the labels that each got.

#9 [#7] Chore : 프로젝트 초기화
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/airbnb09/Airbnb09Application.java
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/airbnb09/Airbnb09ApplicationTests.java
Labels: BE

#11 [FE] 초기 개발환경 설정
  FE/.eslintrc
  FE/.gitignore
  FE/.prettierrc
  FE/babel.config.js
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Test.tsx
  FE/src/index.tsx
  FE/tsconfig.json
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: FE

#13 [BE] Feat : DB 구축
  BE/src/main/resources/airbnb_v1.csv
  BE/src/main/resources/schema.sql
Labels: BE

#19 [FE] 테마, Text, Button 스타일 컴포넌트 제작 완료
  FE/.eslintrc
  FE/package.json
  FE/src/App.jsx
  FE/src/App.tsx
  FE/src/components/Test.jsx
  FE/src/index.jsx
  FE/src/styles/Button.js
  FE/src/styles/GlobalStyle.js
  FE/src/styles/Text.js
  FE/src/styles/mixins.js
  FE/src/styles/theme.js
  FE/tsconfig.json
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: FE, enhancement

#20 [FE] webpack merge 적용하여 중복 제거
  FE/package.json
  FE/webpack.common.js
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: FE

#21 [BE] 목 API 구현
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockController.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockInitResponseDto.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockOneNightRateDto.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockPriceDto.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockSearchRequestDto.java
  BE/src/main/resources/application.properties
Labels: BE

#27 [FE] boilerplate 제작
  FE/src/App.jsx
  FE/src/components/CardList/Card/Card.jsx
  FE/src/components/CardList/Card/Description.jsx
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/CardList/Card/ReservationButton.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/CardList/Title.jsx
  FE/src/components/Filter/Date/Button.jsx
  FE/src/components/Filter/Date/Date.jsx
  FE/src/components/Filter/Date/Modal.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Filter/Guest/Button.jsx
  FE/src/components/Filter/Guest/Guest.jsx
  FE/src/components/Filter/Guest/Modal.jsx
  FE/src/components/Filter/Price/Button.jsx
  FE/src/components/Filter/Price/Modal.jsx
  FE/src/components/Filter/Price/Price.jsx
  FE/src/components/Header/Header.jsx
  FE/src/mock/list.js
Labels: FE

#29 [BE] listing API 구현
  BE/build.gradle
  BE/src/main/java/kr/codesquad/airbnb09/Airbnb09Application.java
  BE/src/main/java/kr/codesquad/airbnb09/domain/AccommodationDTO.java
  BE/src/main/java/kr/codesquad/airbnb09/domain/ListingDAO.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockController.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockInitResponseDto.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockOneNightRateDto.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockPriceDto.java
  BE/src/main/java/kr/codesquad/airbnb09/mock/MockSearchRequestDTO.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ListingController.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/mapper/listingMapper.xml
  BE/src/main/resources/mybatis-config.xml
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/airbnb09/mybatis/DBTest.java
Labels: BE

#33 [FE] 메인페이지 스타일링
  FE/package.json
  FE/src/App.jsx
  FE/src/assets/logo.svg
  FE/src/components/CardList/Card/Card.jsx
  FE/src/components/CardList/Card/Description.jsx
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/CardList/Card/ReservationButton.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/CardList/Title.jsx
  FE/src/components/Filter/Date/Button.jsx
  FE/src/components/Filter/Date/Date.jsx
  FE/src/components/Filter/Date/DateButton.jsx
  FE/src/components/Filter/Date/Modal.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Filter/Guest/Button.jsx
  FE/src/components/Filter/Guest/Guest.jsx
  FE/src/components/Filter/Guest/GuestButton.jsx
  FE/src/components/Filter/Price/Button.jsx
  FE/src/components/Filter/Price/Price.jsx
  FE/src/components/Filter/Price/PriceButton.jsx
  FE/src/components/Header/Header.jsx
  FE/src/styles/Button.js
  FE/src/styles/GlobalStyle.js
  FE/src/styles/theme.js
  FE/tsconfig.json
  FE/webpack.common.js
  FE/yarn.lock
Labels: FE

#35 [FE] 리뷰 내용 적용
  FE/src/styles/mixins.js
  FE/src/styles/theme.js
Labels: FE

#37 [FE] CardList 상태관리 로직 구현 완료
  FE/babel.config.js
  FE/package.json
  FE/src/App.jsx
  FE/src/actions/actions.js
  FE/src/components/CardList/Card/Card.jsx
  FE/src/components/CardList/Card/Description.jsx
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/CardList/Card/ReservationButton.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/CardList/Title.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Header/Header.jsx
  FE/src/contexts/cardListContext.jsx
  FE/src/customHooks/useFetch.jsx
  FE/src/reducers/cardReducer.jsx
  FE/src/styles/Button.js
  FE/src/styles/Text.js
  FE/src/styles/theme.js
  FE/tsconfig.json
  FE/webpack.common.js
  FE/yarn.lock
Labels: FE

#38 [FE] 모달 컴포넌트 스타일링
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Filter/Guest/Guest.jsx
  FE/src/components/Filter/Guest/GuestButton.jsx
  FE/src/components/Filter/Guest/Modal.jsx
  FE/src/styles/Button.js
  FE/src/styles/theme.js
Labels: FE

#44 [FE] Guest 상태관리 구현 완료
  FE/src/App.jsx
  FE/src/actions/actions.js
  FE/src/components/CardList/Card/Card.jsx
  FE/src/components/CardList/Card/Description.jsx
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/CardList/Card/ReservationButton.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/CardList/Title.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Filter/FilterButton.jsx
  FE/src/components/Filter/Guest/Guest.jsx
  FE/src/components/Filter/Guest/GuestButton.jsx
  FE/src/components/Filter/Guest/GuestModal.jsx
  FE/src/components/Filter/Guest/Modal.jsx
  FE/src/components/Filter/Modal.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Test.jsx
  FE/src/contexts/cardListContext.jsx
  FE/src/contexts/filterContext.jsx
  FE/src/customHooks/useFetch.jsx
  FE/src/customHooks/useOutsideClick.jsx
  FE/src/initialStates/initialStates.js
  FE/src/reducers/cardReducer.jsx
  FE/src/reducers/filterReducer.jsx
  FE/src/reducers/guestReducer.jsx
  FE/src/styles/Button.js
  FE/src/styles/Text.js
  FE/tsconfig.json
  FE/webpack.common.js
Labels: FE

#46 [FE] 필터 버튼 클릭 이벤트 중첩 버그 수정
  FE/src/customHooks/useOutsideClick.jsx
Labels: FE, bug
