Repository codesquad-member-2020/airbnb-09, pull requests merged in 2020-06, with the labels that each got.

#47 [BE] search API 구현
  BE/build.gradle
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ListingController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/SearchRequestDTO.java
  BE/src/main/resources/application-deploy.properties
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/mapper/listingMapper.xml
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/airbnb09/mybatis/DBTest.java
  BE/src/test/java/kr/codesquad/airbnb09/web/ListingControllerTest.java
Labels: BE

#50 [BE] 숙소 이미지 데이터 추가
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
  BE/src/main/java/kr/codesquad/airbnb09/web/AllListingDTO.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ImageDTO.java
  BE/src/main/resources/airbnb_image_v2.csv
  BE/src/main/resources/mapper/listingMapper.xml
  BE/src/main/resources/schema.sql
Labels: BE

#53 [FE] 필터링 api 요청 로직 추가 및 리팩토링
  FE/.gitignore
  FE/package.json
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/contexts/cardListContext.jsx
  FE/src/customHooks/useFetch.jsx
  FE/src/customHooks/usePrevious.jsx
  FE/src/initialStates/initialStates.js
  FE/src/reducers/cardReducer.jsx
  FE/src/utils/utils.js
  FE/tsconfig.json
  FE/webpack.common.js
  FE/yarn.lock
Labels: FE

#54 [FE] Fix : Modal 바깥 클릭 버그 수정
  FE/src/components/Filter/Modal.jsx
  FE/src/customHooks/useOutsideClick.jsx
Labels: FE, bug

#57 [FE] 날짜 필터 기능 구현 완료
  FE/package.json
  FE/public/favicon.svg
  FE/src/actions/actions.js
  FE/src/actions/dateAction.js
  FE/src/actions/fetchAction.js
  FE/src/actions/filterAction.js
  FE/src/actions/guestAction.js
  FE/src/components/CardList/CardList.jsx
  FE/src/components/Filter/Date/Date.jsx
  FE/src/components/Filter/Date/DateButton.jsx
  FE/src/components/Filter/Date/DateModal.jsx
  FE/src/components/Filter/Date/Modal.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Filter/Guest/Guest.jsx
  FE/src/components/Filter/Guest/GuestModal.jsx
  FE/src/customHooks/useFetch.jsx
  FE/src/initialStates/initialStates.js
  FE/src/reducers/cardReducer.jsx
  FE/src/reducers/dateReducer.jsx
  FE/src/reducers/filterReducer.jsx
  FE/src/reducers/guestReducer.jsx
  FE/src/utils/urls.js
  FE/src/utils/utils.js
  FE/webpack.common.js
  FE/yarn.lock
Labels: FE

#59 [FE] 달력 모달 스타일링
  FE/src/components/CardList/Card/Description.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/Filter/Date/DateModal.jsx
  FE/src/components/Filter/FilterButton.jsx
  FE/src/mock/list.js
  FE/src/styles/DatesWrapper.js
  FE/src/styles/GlobalStyle.js
  FE/src/styles/theme.js
Labels: FE

#60 [BE] 날짜가 선택되지 않은 경우 가격정보 제외하고 반환하도록 수정
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
  BE/src/main/java/kr/codesquad/airbnb09/web/SearchRequestDTO.java
Labels: BE

#62 [FE] 달력 모달 선택 가능 범위 기능 구현
  FE/src/components/Filter/Date/DateModal.jsx
  FE/src/styles/DateWrapper.js
Labels: FE

#66 [FE] 예약 모달 기능 구현
  FE/src/App.jsx
  FE/src/components/CardList/Card/Card.jsx
  FE/src/components/CardList/Card/Description.jsx
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/CardList/Card/Rating.jsx
  FE/src/components/CardList/Card/ReservationButton.jsx
  FE/src/components/CardList/Card/ReservationModal.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/Filter/Guest/Guest.jsx
  FE/src/constants/constants.js
  FE/src/styles/theme.js
  FE/src/utils/utils.js
  FE/tsconfig.json
  FE/webpack.common.js
Labels: FE

#67 [BE] OAuth 로그인 기능 구현
  BE/build.gradle
  BE/src/main/java/kr/codesquad/airbnb09/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb09/common/error/GlobalExceptionHandler.java
  BE/src/main/java/kr/codesquad/airbnb09/common/error/TokenNotFoundException.java
  BE/src/main/java/kr/codesquad/airbnb09/common/interceptor/JwtInterceptor.java
  BE/src/main/java/kr/codesquad/airbnb09/service/JwtService.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
  BE/src/main/java/kr/codesquad/airbnb09/service/LoginService.java
  BE/src/main/java/kr/codesquad/airbnb09/service/UserMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ReserveController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/GithubToken.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/IndexController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/LoginController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/UserVO.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/mapper/listingMapper.xml
  BE/src/main/resources/schema.sql
  BE/src/main/resources/templates/login.mustache
  BE/src/test/java/kr/codesquad/airbnb09/mybatis/DBTest.java
  FE/src/App.jsx
  FE/src/components/CardList/Card/Card.jsx
  FE/src/components/CardList/Card/Description.jsx
  FE/src/components/CardList/Card/ImageSlider.jsx
  FE/src/components/CardList/Card/Rating.jsx
  FE/src/components/CardList/Card/ReservationButton.jsx
  FE/src/components/CardList/Card/ReservationModal.jsx
  FE/src/components/CardList/CardList.jsx
  FE/src/components/Filter/Date/DateModal.jsx
  FE/src/components/Filter/Guest/Guest.jsx
  FE/src/constants/constants.js
  FE/src/styles/DateWrapper.js
  FE/src/styles/theme.js
  FE/src/utils/utils.js
  FE/tsconfig.json
  FE/webpack.common.js
Labels: BE

#68 [BE] 필터링한 숙소들의 가격 그래프 정보 제공
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ListingController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ResponseListingsDTO.java
  BE/src/main/resources/schema.sql
Labels: BE

#69 [BE] OAuth 로그인 기능 구현 및 필터링된 숙소의 가격 그래프 정보 제공
  BE/build.gradle
  BE/src/main/java/kr/codesquad/airbnb09/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb09/common/error/GlobalExceptionHandler.java
  BE/src/main/java/kr/codesquad/airbnb09/common/error/TokenNotFoundException.java
  BE/src/main/java/kr/codesquad/airbnb09/common/interceptor/JwtInterceptor.java
  BE/src/main/java/kr/codesquad/airbnb09/service/JwtService.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
  BE/src/main/java/kr/codesquad/airbnb09/service/LoginService.java
  BE/src/main/java/kr/codesquad/airbnb09/service/UserMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ListingController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ReserveController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ResponseListingsDTO.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/GithubToken.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/IndexController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/LoginController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/UserVO.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/mapper/listingMapper.xml
  BE/src/main/resources/schema.sql
  BE/src/main/resources/templates/login.mustache
  BE/src/test/java/kr/codesquad/airbnb09/mybatis/DBTest.java
Labels: BE

#70 [BE] 가격 정보 조회 시 에러 처리
  BE/src/main/java/kr/codesquad/airbnb09/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
Labels: BE

#73 [FE] 요금 필터 기능 구현
  FE/package.json
  FE/src/actions/filterAction.js
  FE/src/actions/priceAction.js
  FE/src/components/Filter/Date/Date.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Filter/Modal.jsx
  FE/src/components/Filter/Price/Modal.jsx
  FE/src/components/Filter/Price/Price.jsx
  FE/src/components/Filter/Price/PriceButton.jsx
  FE/src/components/Filter/Price/PriceModal.jsx
  FE/src/components/PriceSlider/components/Histogram/index.jsx
  FE/src/components/PriceSlider/components/RangeInput/index.jsx
  FE/src/components/PriceSlider/components/RangeSlider/components/SliderHandle.jsx
  FE/src/components/PriceSlider/components/RangeSlider/components/SliderRail.jsx
  FE/src/components/PriceSlider/components/RangeSlider/components/SliderTracks.jsx
  FE/src/components/PriceSlider/components/RangeSlider/index.jsx
  FE/src/components/PriceSlider/index.js
  FE/src/customHooks/useFetch.jsx
  FE/src/reducers/filterReducer.jsx
  FE/src/reducers/priceReducer.jsx
  FE/src/utils/urls.js
  FE/src/utils/utils.js
  FE/yarn.lock
Labels: FE

#74 [BE] 페이징 구현
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingMapper.java
  BE/src/main/java/kr/codesquad/airbnb09/service/ListingService.java
  BE/src/main/java/kr/codesquad/airbnb09/web/ListingController.java
  BE/src/main/java/kr/codesquad/airbnb09/web/SearchRequestDTO.java
  BE/src/main/java/kr/codesquad/airbnb09/web/user/LoginController.java
  BE/src/main/resources/mapper/listingMapper.xml
Labels: BE

#75 [FE] OAuth 기능 구현
  FE/package.json
  FE/src/components/CardList/Card/ReservationModal.jsx
  FE/src/components/Filter/Filter.jsx
  FE/src/components/Header/Header.jsx
  FE/src/constants/constants.js
  FE/src/customHooks/useCookie.jsx
  FE/src/styles/DateWrapper.js
  FE/src/utils/urls.js
  FE/src/utils/utils.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: FE

#77 [FE] 최종 배포 전 버그 수정
  FE/src/components/Filter/Date/Date.jsx
  FE/src/utils/utils.js
Labels: FE
